<h1>An error occurred</h1>
<?php 
if ( $this->exception ) {
?>
<h2><?php echo $this->exception->getMessage(); ?></h2>
<hr/>
<h2>Additional information</h2>
<h3><?php echo get_class($this->exception); ?></h3>
<dl>
    <dt>File:</dt>
    <dd>
        <pre class="prettyprint linenums"><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?></pre>
    </dd>
    <dt>Stack trace:</dt>
    <dd>
        <pre class="prettyprint linenums"><?php echo $this->exception->getTraceAsString() ?></pre>
    </dd>
</dl>
<?php 
}
?>