<?php
use Gesfrota\Model\Domain\Notice;
?>
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <title>Sistema de Gestão de Frotas</title>
        <link rel="stylesheet" href="/vendor/bootstrap/bootstrap-2.3.2.css" type="text/css" media="all" />
        <link rel="stylesheet" href="/vendor/bootstrap/bootstrap-responsive-2.3.2.css" type="text/css" media="all" />
		<link rel="stylesheet" href="/vendor/bootstrap-datepicker/bootstrap-datepicker.css" type="text/css" media="all" />
		<link rel="stylesheet" href="/vendor/bootstrap-timepicker/bootstrap-timepicker-0.2.3.css" type="text/css" media="all" />
		<link rel="stylesheet" href="/vendor/bootstrap-colorpicker/bootstrap-colorpicker.css" type="text/css" media="all" />
		<link rel="stylesheet" href="/vendor/chosen/chosen-1.0.0.min.css" type="text/css" media="all" />
		<link rel="stylesheet" href="/vendor/phpbootstrap/phpbootstrap.css" type="text/css" media="all" />
		<link rel="stylesheet" href="/css/application.css" type="text/css" media="all" />
		
		<script type="text/javascript" src="/vendor/jquery-1.8.2.js"></script>
		<script type="text/javascript" src="/vendor/jquery.ui.core-1.10.3.js"></script>
		<script type="text/javascript" src="/vendor/jquery.ui.widget-1.10.3.js"></script>
		<script type="text/javascript" src="/vendor/jquery.ui.mouse-1.10.3.js"></script>
		<script type="text/javascript" src="/vendor/jquery.ui.sortable-1.10.3.js"></script>
		<script type="text/javascript" src="/vendor/jquery.ui.draggable-1.10.3.js"></script>
		<script type="text/javascript" src="/vendor/jquery.ui.droppable-1.10.3.js"></script>
		<script type="text/javascript" src="/vendor/jquery.cookie-1.3.1.js"></script>
		<script type="text/javascript" src="/vendor/jquery.form-3.20.js"></script>
		<script type="text/javascript" src="/vendor/jquery.validate-1.10.0.js"></script>
		<script type="text/javascript" src="/vendor/jquery.validate-1.10.0.add.methods.js"></script>
		<script type="text/javascript" src="/vendor/jquery.maskmoney-1.3.js"></script>
		<script type="text/javascript" src="/vendor/jquery.maskedinput-1.4.1.js"></script>
		<script type="text/javascript" src="/vendor/jquery.fckeditor-1.32.js"></script>
		<script type="text/javascript" src="/vendor/fckeditor/fckeditor.js"></script>
    </head>
    <body>
    	<div id="main">
	    	<?php  if ($this->navbar) { $this->navbar->render(); } ?>
	    	<?php if ($this->notice instanceof Notice ) {?>
	    	<div id="notice-body" class="notification">
	    		<div class="container">
               		<?php echo str_replace('{notice-read-current}', '/notice/read/' . $this->notice->id, $this->notice->getBody()); ?>
               </div>
            </div>
            <?php } ?>
	    	<div class="container">
	            <?php echo $this->__CONTENT__; ?>
	        </div>
        </div>
        <?php if ($this->about) { $this->about->render(); } ?>
        <footer>
        	<div class="container-fluid">
	        	<hr><p class="muted">Copyright © <?php echo date('Y'); ?> Gesfrota v<?php echo json_decode(file_get_contents('composer.json', true))->version; ?> | Development by <a href="#">Iduardo Junior</a></p>
	        </div>
        </footer>
        <script type="text/javascript" src="/vendor/bootstrap/bootstrap-2.3.2.js"></script>
		<script type="text/javascript" src="/vendor/bootstrap-datepicker/bootstrap-datepicker.js"></script>
		<script type="text/javascript" src="/vendor/bootstrap-datepicker/locales/bootstrap-datepicker.pt-BR.js"></script>
		<script type="text/javascript" src="/vendor/bootstrap-timepicker/bootstrap-timepicker-0.2.3.js"></script>
		<script type="text/javascript" src="/vendor/bootstrap-colorpicker/bootstrap-colorpicker.js"></script>
		<script type="text/javascript" src="/vendor/chosen/chosen-1.0.0.min.js"></script>
		<script type="text/javascript">$(function() {$.fck.path = '/vendor/fckeditor/'; });</script>
		<script type="text/javascript" src="/vendor/phpbootstrap/phpbootstrap.js"></script>
		<script src="https://maps.googleapis.com/maps/api/js?key=<?php echo GOOGLE_KEY_APP;?>&v=weekly"></script>
		<script type="text/javascript" src="/js/directions.js"></script>
		<script type="text/javascript" src="/js/place-input.js"></script>
		<script type="text/javascript" src="/js/dyn-input.js"></script>
		<script type="text/javascript" src="/js/application.js"></script>
    </body>
</html>