<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <title>Sistema de Gestão de Materiais</title>
        <link rel="stylesheet" href="/vendor/bootstrap/bootstrap-2.3.2.css" type="text/css" media="all" />
        <link rel="stylesheet" href="/vendor/bootstrap/bootstrap-responsive-2.3.2.css" type="text/css" media="all" />
		<link rel="stylesheet" href="/vendor/bootstrap-datepicker/bootstrap-datepicker.css" type="text/css" media="all" />
		<link rel="stylesheet" href="/vendor/bootstrap-timepicker/bootstrap-timepicker-0.2.3.css" type="text/css" media="all" />
		<link rel="stylesheet" href="/vendor/bootstrap-colorpicker/bootstrap-colorpicker.css" type="text/css" media="all" />
		<link rel="stylesheet" href="/vendor/phpbootstrap/phpbootstrap-1.0.0.min.css" type="text/css" media="all" />
		<link rel="stylesheet" href="/css/application.css" type="text/css" media="all" />
		
		<script type="text/javascript" src="/vendor/jquery-1.8.2.js"></script>
		<script type="text/javascript" src="/vendor/jquery.form-3.20.js"></script>
		<script type="text/javascript" src="/vendor/jquery.validate-1.10.0.js"></script>
		<script type="text/javascript" src="/vendor/jquery.validate-1.10.0.add.methods.js"></script>
		<script type="text/javascript" src="/vendor/jquery.maskmoney-1.3.js"></script>
		<script type="text/javascript" src="/vendor/jquery.maskedinput-1.3.js"></script>
		<script type="text/javascript" src="/vendor/jquery.fckeditor-1.32.js"></script>
		<script type="text/javascript" src="/vendor/fckeditor/fckeditor.js"></script>
    </head>
    <body>
    	<div id="main">
	    	<?php $this->__NAVBAR__->render(); ?>
	    	<div class="container">
	            <?php echo $this->__CONTENT__; ?>
	        </div>
        </div>
        <footer>
        	<div class="container-fluid">
	        	<hr><p class="muted">Copyright © <?php echo date('Y'); ?> Sigmat v1.0 | Development by <a href="http://iduardojunior.com.br">Iduardo Junior</a></p>
	        </div>
        </footer>
        <script type="text/javascript" src="/vendor/bootstrap/bootstrap-2.3.2.js"></script>
		<script type="text/javascript" src="/vendor/bootstrap-datepicker/bootstrap-datepicker.js"></script>
		<script type="text/javascript" src="/vendor/bootstrap-datepicker/locales/bootstrap-datepicker.pt-BR.js"></script>
		<script type="text/javascript" src="/vendor/bootstrap-timepicker/bootstrap-timepicker-0.2.3.js"></script>
		<script type="text/javascript" src="/vendor/bootstrap-colorpicker/bootstrap-colorpicker.js"></script>
		<script type="text/javascript" src="/vendor/phpbootstrap/phpbootstrap-1.0.0.min.js"></script>
		<script type="text/javascript" src="/js/application.js"></script>
    </body>
</html>