<form class="form-signin" method="post" action="/auth/reset-password">
	<h1 class="form-signin-heading">
		<span class="brand">Esqueci minha senha</span>
		<img src="/images/brand.png" alt="Governo de Goiás">
	</h1>
	<?php if ($this->message) { ?>
	<p class="text-left"><?php echo $this->message; ?></p>
	<?php } ?>
	<input type="text" class="input-block-level" name="login" placeholder="Digite seu CPF" data-mask="999.999.999-99">
	<a class="btn btn-link" href="/auth">Cancelar</a>
	<button class="btn btn-large btn-success" type="submit">Redefinir senha</button>
</form>
<style type="text/css">
body {
	padding-top: 40px;
	padding-bottom: 40px;
	background-color: #f5f5f5;
}
</style>