<?php

namespace DoctrineProxies\__CG__\Gesfrota\Model\Domain;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Survey extends \Gesfrota\Model\Domain\Survey implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * {@inheritDoc}
     * @param string $name
     */
    public function __get($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', [$name]);
        return parent::__get($name);
    }

    /**
     * {@inheritDoc}
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);
        return parent::__set($name, $value);
    }



    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'lanternFrontLeft', 'lanternFrontRight', 'lanternBackLeft', 'lanternBackRight', 'lanternArrowFrontLeft', 'lanternArrowFrontRight', 'lanternArrowBackLeft', 'lanternArrowBackRight', 'bumperFront', 'bumperBack', 'coverFront', 'coverBack', 'windshieldFront', 'windshieldBack', 'roof', 'exhaust', 'windowFrontLeft', 'windowFrontRight', 'windowBackLeft', 'windowBackRight', 'doorFrontLeft', 'doorFrontRight', 'doorBackLeft', 'doorBackRight', 'columnFrontLeft', 'columnFrontRight', 'columnBackLeft', 'columnBackRight', 'stirrupFrontLeft', 'stirrupFrontRight', 'stirrupBackLeft', 'stirrupBackRight', 'fenderFrontLeft', 'fenderFrontRight', 'fenderBackLeft', 'fenderBackRight', 'tireFrontLeft', 'tireFrontRight', 'tireBackLeft', 'tireBackRight', 'seatDriver', 'seatPassenger', 'seatRear', 'dashboard', 'steeringWheel', 'horn', 'centralConsole', 'roofTapestry', 'trunkCap', 'doorLining', 'airConditioning', 'alarm', 'steeringHydraulic', 'deviceSound', 'electricGlass', 'electricLock', 'carpet', 'wheelIron', 'wheelAlloy', 'lanternFog', 'carburetor', 'exchange', 'differential', 'engine', 'radiator', 'turbine', 'suspension', 'injectionPump', 'injectionNozzle', 'injectionElectronic', 'gasolineBump', 'engineStarter', 'ignitionModule', 'alternator', 'distributor', 'battery', 'safetyBelts', 'airbag', 'rearviewInternal', 'rearviewLeft', 'rearviewRight', 'safetyTriangle', 'monkey', 'wheelWrench', 'wheelSpare', 'note', 'id'];
        }

        return ['__isInitialized__', 'lanternFrontLeft', 'lanternFrontRight', 'lanternBackLeft', 'lanternBackRight', 'lanternArrowFrontLeft', 'lanternArrowFrontRight', 'lanternArrowBackLeft', 'lanternArrowBackRight', 'bumperFront', 'bumperBack', 'coverFront', 'coverBack', 'windshieldFront', 'windshieldBack', 'roof', 'exhaust', 'windowFrontLeft', 'windowFrontRight', 'windowBackLeft', 'windowBackRight', 'doorFrontLeft', 'doorFrontRight', 'doorBackLeft', 'doorBackRight', 'columnFrontLeft', 'columnFrontRight', 'columnBackLeft', 'columnBackRight', 'stirrupFrontLeft', 'stirrupFrontRight', 'stirrupBackLeft', 'stirrupBackRight', 'fenderFrontLeft', 'fenderFrontRight', 'fenderBackLeft', 'fenderBackRight', 'tireFrontLeft', 'tireFrontRight', 'tireBackLeft', 'tireBackRight', 'seatDriver', 'seatPassenger', 'seatRear', 'dashboard', 'steeringWheel', 'horn', 'centralConsole', 'roofTapestry', 'trunkCap', 'doorLining', 'airConditioning', 'alarm', 'steeringHydraulic', 'deviceSound', 'electricGlass', 'electricLock', 'carpet', 'wheelIron', 'wheelAlloy', 'lanternFog', 'carburetor', 'exchange', 'differential', 'engine', 'radiator', 'turbine', 'suspension', 'injectionPump', 'injectionNozzle', 'injectionElectronic', 'gasolineBump', 'engineStarter', 'ignitionModule', 'alternator', 'distributor', 'battery', 'safetyBelts', 'airbag', 'rearviewInternal', 'rearviewLeft', 'rearviewRight', 'safetyTriangle', 'monkey', 'wheelWrench', 'wheelSpare', 'note', 'id'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Survey $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getLanternFrontLeft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanternFrontLeft', []);

        return parent::getLanternFrontLeft();
    }

    /**
     * {@inheritDoc}
     */
    public function getLanternFrontRight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanternFrontRight', []);

        return parent::getLanternFrontRight();
    }

    /**
     * {@inheritDoc}
     */
    public function getLanternBackLeft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanternBackLeft', []);

        return parent::getLanternBackLeft();
    }

    /**
     * {@inheritDoc}
     */
    public function getLanternBackRight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanternBackRight', []);

        return parent::getLanternBackRight();
    }

    /**
     * {@inheritDoc}
     */
    public function getLanternArrowFrontLeft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanternArrowFrontLeft', []);

        return parent::getLanternArrowFrontLeft();
    }

    /**
     * {@inheritDoc}
     */
    public function getLanternArrowFrontRight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanternArrowFrontRight', []);

        return parent::getLanternArrowFrontRight();
    }

    /**
     * {@inheritDoc}
     */
    public function getLanternArrowBackLeft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanternArrowBackLeft', []);

        return parent::getLanternArrowBackLeft();
    }

    /**
     * {@inheritDoc}
     */
    public function getLanternArrowBackRight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanternArrowBackRight', []);

        return parent::getLanternArrowBackRight();
    }

    /**
     * {@inheritDoc}
     */
    public function getBumperFront()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBumperFront', []);

        return parent::getBumperFront();
    }

    /**
     * {@inheritDoc}
     */
    public function getBumperBack()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBumperBack', []);

        return parent::getBumperBack();
    }

    /**
     * {@inheritDoc}
     */
    public function getCoverFront()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoverFront', []);

        return parent::getCoverFront();
    }

    /**
     * {@inheritDoc}
     */
    public function getCoverBack()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoverBack', []);

        return parent::getCoverBack();
    }

    /**
     * {@inheritDoc}
     */
    public function getWindshieldFront()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWindshieldFront', []);

        return parent::getWindshieldFront();
    }

    /**
     * {@inheritDoc}
     */
    public function getWindshieldBack()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWindshieldBack', []);

        return parent::getWindshieldBack();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoof()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoof', []);

        return parent::getRoof();
    }

    /**
     * {@inheritDoc}
     */
    public function getExhaust()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExhaust', []);

        return parent::getExhaust();
    }

    /**
     * {@inheritDoc}
     */
    public function getWindowFrontLeft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWindowFrontLeft', []);

        return parent::getWindowFrontLeft();
    }

    /**
     * {@inheritDoc}
     */
    public function getWindowFrontRight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWindowFrontRight', []);

        return parent::getWindowFrontRight();
    }

    /**
     * {@inheritDoc}
     */
    public function getWindowBackLeft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWindowBackLeft', []);

        return parent::getWindowBackLeft();
    }

    /**
     * {@inheritDoc}
     */
    public function getWindowBackRight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWindowBackRight', []);

        return parent::getWindowBackRight();
    }

    /**
     * {@inheritDoc}
     */
    public function getDoorFrontLeft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDoorFrontLeft', []);

        return parent::getDoorFrontLeft();
    }

    /**
     * {@inheritDoc}
     */
    public function getDoorFrontRight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDoorFrontRight', []);

        return parent::getDoorFrontRight();
    }

    /**
     * {@inheritDoc}
     */
    public function getDoorBackLeft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDoorBackLeft', []);

        return parent::getDoorBackLeft();
    }

    /**
     * {@inheritDoc}
     */
    public function getDoorBackRight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDoorBackRight', []);

        return parent::getDoorBackRight();
    }

    /**
     * {@inheritDoc}
     */
    public function getColumnFrontLeft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColumnFrontLeft', []);

        return parent::getColumnFrontLeft();
    }

    /**
     * {@inheritDoc}
     */
    public function getColumnFrontRight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColumnFrontRight', []);

        return parent::getColumnFrontRight();
    }

    /**
     * {@inheritDoc}
     */
    public function getColumnBackLeft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColumnBackLeft', []);

        return parent::getColumnBackLeft();
    }

    /**
     * {@inheritDoc}
     */
    public function getColumnBackRight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColumnBackRight', []);

        return parent::getColumnBackRight();
    }

    /**
     * {@inheritDoc}
     */
    public function getStirrupFrontLeft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStirrupFrontLeft', []);

        return parent::getStirrupFrontLeft();
    }

    /**
     * {@inheritDoc}
     */
    public function getStirrupFrontRight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStirrupFrontRight', []);

        return parent::getStirrupFrontRight();
    }

    /**
     * {@inheritDoc}
     */
    public function getStirrupBackLeft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStirrupBackLeft', []);

        return parent::getStirrupBackLeft();
    }

    /**
     * {@inheritDoc}
     */
    public function getStirrupBackRight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStirrupBackRight', []);

        return parent::getStirrupBackRight();
    }

    /**
     * {@inheritDoc}
     */
    public function getFenderFrontLeft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFenderFrontLeft', []);

        return parent::getFenderFrontLeft();
    }

    /**
     * {@inheritDoc}
     */
    public function getFenderFrontRight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFenderFrontRight', []);

        return parent::getFenderFrontRight();
    }

    /**
     * {@inheritDoc}
     */
    public function getFenderBackLeft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFenderBackLeft', []);

        return parent::getFenderBackLeft();
    }

    /**
     * {@inheritDoc}
     */
    public function getFenderBackRight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFenderBackRight', []);

        return parent::getFenderBackRight();
    }

    /**
     * {@inheritDoc}
     */
    public function getTireFrontLeft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTireFrontLeft', []);

        return parent::getTireFrontLeft();
    }

    /**
     * {@inheritDoc}
     */
    public function getTireFrontRight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTireFrontRight', []);

        return parent::getTireFrontRight();
    }

    /**
     * {@inheritDoc}
     */
    public function getTireBackLeft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTireBackLeft', []);

        return parent::getTireBackLeft();
    }

    /**
     * {@inheritDoc}
     */
    public function getTireBackRight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTireBackRight', []);

        return parent::getTireBackRight();
    }

    /**
     * {@inheritDoc}
     */
    public function getSeatDriver()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeatDriver', []);

        return parent::getSeatDriver();
    }

    /**
     * {@inheritDoc}
     */
    public function getSeatPassenger()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeatPassenger', []);

        return parent::getSeatPassenger();
    }

    /**
     * {@inheritDoc}
     */
    public function getSeatRear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeatRear', []);

        return parent::getSeatRear();
    }

    /**
     * {@inheritDoc}
     */
    public function getDashboard()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDashboard', []);

        return parent::getDashboard();
    }

    /**
     * {@inheritDoc}
     */
    public function getSteeringWheel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSteeringWheel', []);

        return parent::getSteeringWheel();
    }

    /**
     * {@inheritDoc}
     */
    public function getHorn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorn', []);

        return parent::getHorn();
    }

    /**
     * {@inheritDoc}
     */
    public function getCentralConsole()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCentralConsole', []);

        return parent::getCentralConsole();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoofTapestry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoofTapestry', []);

        return parent::getRoofTapestry();
    }

    /**
     * {@inheritDoc}
     */
    public function getTrunkCap()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrunkCap', []);

        return parent::getTrunkCap();
    }

    /**
     * {@inheritDoc}
     */
    public function getDoorLining()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDoorLining', []);

        return parent::getDoorLining();
    }

    /**
     * {@inheritDoc}
     */
    public function getAirConditioning()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAirConditioning', []);

        return parent::getAirConditioning();
    }

    /**
     * {@inheritDoc}
     */
    public function getAlarm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlarm', []);

        return parent::getAlarm();
    }

    /**
     * {@inheritDoc}
     */
    public function getSteeringHydraulic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSteeringHydraulic', []);

        return parent::getSteeringHydraulic();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeviceSound()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeviceSound', []);

        return parent::getDeviceSound();
    }

    /**
     * {@inheritDoc}
     */
    public function getElectricGlass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getElectricGlass', []);

        return parent::getElectricGlass();
    }

    /**
     * {@inheritDoc}
     */
    public function getElectricLock()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getElectricLock', []);

        return parent::getElectricLock();
    }

    /**
     * {@inheritDoc}
     */
    public function getCarpet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarpet', []);

        return parent::getCarpet();
    }

    /**
     * {@inheritDoc}
     */
    public function getWheelIron()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWheelIron', []);

        return parent::getWheelIron();
    }

    /**
     * {@inheritDoc}
     */
    public function getWheelAlloy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWheelAlloy', []);

        return parent::getWheelAlloy();
    }

    /**
     * {@inheritDoc}
     */
    public function getLanternFog()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanternFog', []);

        return parent::getLanternFog();
    }

    /**
     * {@inheritDoc}
     */
    public function getCarburetor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarburetor', []);

        return parent::getCarburetor();
    }

    /**
     * {@inheritDoc}
     */
    public function getExchange()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExchange', []);

        return parent::getExchange();
    }

    /**
     * {@inheritDoc}
     */
    public function getDifferential()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDifferential', []);

        return parent::getDifferential();
    }

    /**
     * {@inheritDoc}
     */
    public function getEngine()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEngine', []);

        return parent::getEngine();
    }

    /**
     * {@inheritDoc}
     */
    public function getRadiator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRadiator', []);

        return parent::getRadiator();
    }

    /**
     * {@inheritDoc}
     */
    public function getTurbine()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTurbine', []);

        return parent::getTurbine();
    }

    /**
     * {@inheritDoc}
     */
    public function getSuspension()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSuspension', []);

        return parent::getSuspension();
    }

    /**
     * {@inheritDoc}
     */
    public function getInjectionPump()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInjectionPump', []);

        return parent::getInjectionPump();
    }

    /**
     * {@inheritDoc}
     */
    public function getInjectionNozzle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInjectionNozzle', []);

        return parent::getInjectionNozzle();
    }

    /**
     * {@inheritDoc}
     */
    public function getInjectionElectronic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInjectionElectronic', []);

        return parent::getInjectionElectronic();
    }

    /**
     * {@inheritDoc}
     */
    public function getGasolineBump()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGasolineBump', []);

        return parent::getGasolineBump();
    }

    /**
     * {@inheritDoc}
     */
    public function getEngineStarter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEngineStarter', []);

        return parent::getEngineStarter();
    }

    /**
     * {@inheritDoc}
     */
    public function getIgnitionModule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIgnitionModule', []);

        return parent::getIgnitionModule();
    }

    /**
     * {@inheritDoc}
     */
    public function getAlternator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlternator', []);

        return parent::getAlternator();
    }

    /**
     * {@inheritDoc}
     */
    public function getDistributor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDistributor', []);

        return parent::getDistributor();
    }

    /**
     * {@inheritDoc}
     */
    public function getBattery()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBattery', []);

        return parent::getBattery();
    }

    /**
     * {@inheritDoc}
     */
    public function getSafetyBelts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSafetyBelts', []);

        return parent::getSafetyBelts();
    }

    /**
     * {@inheritDoc}
     */
    public function getAirbag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAirbag', []);

        return parent::getAirbag();
    }

    /**
     * {@inheritDoc}
     */
    public function getRearviewInternal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRearviewInternal', []);

        return parent::getRearviewInternal();
    }

    /**
     * {@inheritDoc}
     */
    public function getRearviewLeft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRearviewLeft', []);

        return parent::getRearviewLeft();
    }

    /**
     * {@inheritDoc}
     */
    public function getRearviewRight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRearviewRight', []);

        return parent::getRearviewRight();
    }

    /**
     * {@inheritDoc}
     */
    public function getSafetyTriangle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSafetyTriangle', []);

        return parent::getSafetyTriangle();
    }

    /**
     * {@inheritDoc}
     */
    public function getMonkey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMonkey', []);

        return parent::getMonkey();
    }

    /**
     * {@inheritDoc}
     */
    public function getWheelWrench()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWheelWrench', []);

        return parent::getWheelWrench();
    }

    /**
     * {@inheritDoc}
     */
    public function getWheelSpare()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWheelSpare', []);

        return parent::getWheelSpare();
    }

    /**
     * {@inheritDoc}
     */
    public function getNote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNote', []);

        return parent::getNote();
    }

    /**
     * {@inheritDoc}
     */
    public function setLanternFrontLeft($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLanternFrontLeft', [$status]);

        return parent::setLanternFrontLeft($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setLanternFrontRight($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLanternFrontRight', [$status]);

        return parent::setLanternFrontRight($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setLanternBackLeft($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLanternBackLeft', [$status]);

        return parent::setLanternBackLeft($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setLanternBackRight($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLanternBackRight', [$status]);

        return parent::setLanternBackRight($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setLanternArrowFrontLeft($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLanternArrowFrontLeft', [$status]);

        return parent::setLanternArrowFrontLeft($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setLanternArrowFrontRight($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLanternArrowFrontRight', [$status]);

        return parent::setLanternArrowFrontRight($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setLanternArrowBackLeft($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLanternArrowBackLeft', [$status]);

        return parent::setLanternArrowBackLeft($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setLanternArrowBackRight($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLanternArrowBackRight', [$status]);

        return parent::setLanternArrowBackRight($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setBumperFront($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBumperFront', [$status]);

        return parent::setBumperFront($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setBumperBack($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBumperBack', [$status]);

        return parent::setBumperBack($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setCoverFront($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoverFront', [$status]);

        return parent::setCoverFront($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setCoverBack($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoverBack', [$status]);

        return parent::setCoverBack($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setWindshieldFront($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWindshieldFront', [$status]);

        return parent::setWindshieldFront($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setWindshieldBack($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWindshieldBack', [$status]);

        return parent::setWindshieldBack($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setRoof($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoof', [$status]);

        return parent::setRoof($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setExhaust($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExhaust', [$status]);

        return parent::setExhaust($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setWindowFrontLeft($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWindowFrontLeft', [$status]);

        return parent::setWindowFrontLeft($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setWindowFrontRight($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWindowFrontRight', [$status]);

        return parent::setWindowFrontRight($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setWindowBackLeft($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWindowBackLeft', [$status]);

        return parent::setWindowBackLeft($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setWindowBackRight($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWindowBackRight', [$status]);

        return parent::setWindowBackRight($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setDoorFrontLeft($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDoorFrontLeft', [$status]);

        return parent::setDoorFrontLeft($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setDoorFrontRight($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDoorFrontRight', [$status]);

        return parent::setDoorFrontRight($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setDoorBackLeft($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDoorBackLeft', [$status]);

        return parent::setDoorBackLeft($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setDoorBackRight($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDoorBackRight', [$status]);

        return parent::setDoorBackRight($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setColumnFrontLeft($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColumnFrontLeft', [$status]);

        return parent::setColumnFrontLeft($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setColumnFrontRight($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColumnFrontRight', [$status]);

        return parent::setColumnFrontRight($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setColumnBackLeft($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColumnBackLeft', [$status]);

        return parent::setColumnBackLeft($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setColumnBackRight($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColumnBackRight', [$status]);

        return parent::setColumnBackRight($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setStirrupFrontLeft($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStirrupFrontLeft', [$status]);

        return parent::setStirrupFrontLeft($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setStirrupFrontRight($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStirrupFrontRight', [$status]);

        return parent::setStirrupFrontRight($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setStirrupBackLeft($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStirrupBackLeft', [$status]);

        return parent::setStirrupBackLeft($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setStirrupBackRight($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStirrupBackRight', [$status]);

        return parent::setStirrupBackRight($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setFenderFrontLeft($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFenderFrontLeft', [$status]);

        return parent::setFenderFrontLeft($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setFenderFrontRight($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFenderFrontRight', [$status]);

        return parent::setFenderFrontRight($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setFenderBackLeft($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFenderBackLeft', [$status]);

        return parent::setFenderBackLeft($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setFenderBackRight($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFenderBackRight', [$status]);

        return parent::setFenderBackRight($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setTireFrontLeft($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTireFrontLeft', [$status]);

        return parent::setTireFrontLeft($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setTireFrontRight($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTireFrontRight', [$status]);

        return parent::setTireFrontRight($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setTireBackLeft($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTireBackLeft', [$status]);

        return parent::setTireBackLeft($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setTireBackRight($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTireBackRight', [$status]);

        return parent::setTireBackRight($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setSeatDriver($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeatDriver', [$status]);

        return parent::setSeatDriver($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setSeatPassenger($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeatPassenger', [$status]);

        return parent::setSeatPassenger($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setSeatRear($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeatRear', [$status]);

        return parent::setSeatRear($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setDashboard($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDashboard', [$status]);

        return parent::setDashboard($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setSteeringWheel($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSteeringWheel', [$status]);

        return parent::setSteeringWheel($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setHorn($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorn', [$status]);

        return parent::setHorn($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setCentralConsole($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCentralConsole', [$status]);

        return parent::setCentralConsole($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setRoofTapestry($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoofTapestry', [$status]);

        return parent::setRoofTapestry($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setTrunkCap($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrunkCap', [$status]);

        return parent::setTrunkCap($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setDoorLining($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDoorLining', [$status]);

        return parent::setDoorLining($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setAirConditioning($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAirConditioning', [$status]);

        return parent::setAirConditioning($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setAlarm($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlarm', [$status]);

        return parent::setAlarm($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setSteeringHydraulic($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSteeringHydraulic', [$status]);

        return parent::setSteeringHydraulic($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setDeviceSound($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeviceSound', [$status]);

        return parent::setDeviceSound($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setElectricGlass($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setElectricGlass', [$status]);

        return parent::setElectricGlass($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setElectricLock($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setElectricLock', [$status]);

        return parent::setElectricLock($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setCarpet($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarpet', [$status]);

        return parent::setCarpet($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setWheelIron($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWheelIron', [$status]);

        return parent::setWheelIron($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setWheelAlloy($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWheelAlloy', [$status]);

        return parent::setWheelAlloy($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setLanternFog($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLanternFog', [$status]);

        return parent::setLanternFog($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setCarburetor($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarburetor', [$status]);

        return parent::setCarburetor($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setExchange($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExchange', [$status]);

        return parent::setExchange($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setDifferential($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDifferential', [$status]);

        return parent::setDifferential($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setEngine($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEngine', [$status]);

        return parent::setEngine($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setRadiator($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRadiator', [$status]);

        return parent::setRadiator($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setTurbine($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTurbine', [$status]);

        return parent::setTurbine($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setSuspension($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuspension', [$status]);

        return parent::setSuspension($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setInjectionPump($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInjectionPump', [$status]);

        return parent::setInjectionPump($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setInjectionNozzle($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInjectionNozzle', [$status]);

        return parent::setInjectionNozzle($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setInjectionElectronic($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInjectionElectronic', [$status]);

        return parent::setInjectionElectronic($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setGasolineBump($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGasolineBump', [$status]);

        return parent::setGasolineBump($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setEngineStarter($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEngineStarter', [$status]);

        return parent::setEngineStarter($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setIgnitionModule($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIgnitionModule', [$status]);

        return parent::setIgnitionModule($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setAlternator($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlternator', [$status]);

        return parent::setAlternator($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setDistributor($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDistributor', [$status]);

        return parent::setDistributor($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setBattery($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBattery', [$status]);

        return parent::setBattery($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setSafetyBelts($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSafetyBelts', [$status]);

        return parent::setSafetyBelts($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setAirbag($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAirbag', [$status]);

        return parent::setAirbag($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setRearviewInternal($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRearviewInternal', [$status]);

        return parent::setRearviewInternal($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setRearviewLeft($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRearviewLeft', [$status]);

        return parent::setRearviewLeft($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setRearviewRight($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRearviewRight', [$status]);

        return parent::setRearviewRight($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setSafetyTriangle($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSafetyTriangle', [$status]);

        return parent::setSafetyTriangle($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setMonkey($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMonkey', [$status]);

        return parent::setMonkey($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setWheelWrench($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWheelWrench', [$status]);

        return parent::setWheelWrench($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setWheelSpare($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWheelSpare', [$status]);

        return parent::setWheelSpare($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setNote($note)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNote', [$note]);

        return parent::setNote($note);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

}
