<?php
use Gesfrota\Services\Log;
use Gesfrota\Model\Domain\Vehicle;
use Gesfrota\Model\Domain\RequestTrip;
use Gesfrota\Model\Domain\Request;
use Gesfrota\Model\Domain\Requester;
use Gesfrota\Util\Format;
?>
<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
<div class="page-header">
	<form action="/" method="post" class="form-inline pull-right" style="display: inline-block; margin: 14px 0;">
		<label>Período</label>
		<input type="hidden" name="tab-active" id="tab-active" value="<?php echo $this->tab_active; ?>">
		<input type="text" class="input-small" placeholder="Data Inicial" value="<?php echo $this->initial->format('m/Y'); ?>" name="initial" data-mask="99/9999">
  		<input type="text" class="input-small" placeholder="Data Final" value="<?php echo $this->final->format('m/Y'); ?>" name="final" data-mask="99/9999">
  		<button type="submit" class="btn">Filtrar</button>
	</form>
	<h1>Dashboard <small>KIP's</small></h1>
	<ul class="nav nav-pills">
        <li<?php echo $this->tab_active == 'request' ? ' class="active"' : ''; ?>><a href="#tab-request" data-toggle="pill">Requisições</a></li>
        <li<?php echo $this->tab_active == 'fleet' ? ' class="active"' : ''; ?>><a href="#tab-fleet" data-toggle="pill">Frota</a></li>
        <li<?php echo $this->tab_active == 'fuel' ? ' class="active"' : ''; ?>><a href="#tab-fuel" data-toggle="pill">Abastecimento</a></li>
        <li class="disabled"><a href="#">Manutenção</a></li>
    </ul>
</div>
<div id="dashboard" class="tabbable">
  	<div class="tab-content">
    	<div class="tab-pane<?php echo $this->tab_active == 'request' ? ' active' : ''; ?>" id="tab-request">
          	<?php include 'index-request.phtml'; ?>
    	</div>
        <div class="tab-pane<?php echo $this->tab_active == 'fleet' ? ' active' : ''; ?>" id="tab-fleet">
        	<?php include 'index-fleet.phtml'; ?>
        </div>
        <div class="tab-pane<?php echo $this->tab_active == 'fuel' ? ' active' : ''; ?>" id="tab-fuel">
          	<?php include 'index-fuel.phtml'; ?>
        </div>
  	</div>
</div>
<script>
$('a[data-toggle="pill"]').on('shown', function (e) {
  $('#tab-active').val($(e.target).attr('href').replace('#tab-', ''));
})
</script>