<?php
use Gesfrota\Services\Log;
use Gesfrota\Model\Domain\Vehicle;
use Gesfrota\Model\Domain\RequestTrip;
use Gesfrota\Model\Domain\Request;
use Gesfrota\Model\Domain\Requester;
?>
<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
<div class="page-header">
	<form action="/" method="post" class="form-inline pull-right" style="display: inline-block; margin: 7px;">
		<label>Período</label>
		<input type="text" class="input-small" placeholder="Data Inicial" value="<?php echo $this->initial->format('m/Y'); ?>" name="initial" data-mask="99/9999">
  		<input type="text" class="input-small" placeholder="Data Final" value="<?php echo $this->final->format('m/Y'); ?>" name="final" data-mask="99/9999">
  		<button type="submit" class="btn">Filtrar</button>
	</form>
	<h1>Dashboard <small>Indicadores de Desempenho</small></h1>
</div>
<div id="dashboard">
<div class="row-fluid">
	<div class="span3">
		<div class="card">
  			<div class="header">
  				<strong><?php echo number_format($this->KPIs['request_total'], 0, '', '.'); ?></strong>
  				<small>Requisições Abertas</small>
  			</div>
  		</div>
	</div>
	<div class="span3">
	  	<div class="card">
			<div class="header">
		  		<strong><?php echo number_format($this->KPIs['request_declined'], 0, '', '.'); ?></strong>
				<small>Requisições Recusadas</small>
	  		</div>
	  	</div>
	</div>
	<div class="span3">
	  	<div class="card">
			<div class="header">
		  		<strong><?php echo number_format($this->KPIs['request_finished'], 0, '', '.'); ?></strong>
				<small>Requisições Atendidas</small>
	  		</div>
	  	</div>
	</div>
	<div class="span3">
	  	<div class="card">
			<div class="header">
		  		<strong><?php echo number_format($this->KPIs['request_distance'], 1, ',', '.'); ?> Km</strong>
				<small>Percorridos</small>
	  		</div>
	  	</div>
	</div>
</div>
<hr>
<div class="row-fluid">
	<div class="span3">
		<h3><span class="header">Índice de Atendimento<small>Percentual das requisições disponibilizadas</small></span></h3>
		<div id="request-availability"></div>
  		<script>
			var options = {
				series: [<?php echo number_format($this->KPIs['request_availability']*100, 1); ?>],
				chart: {
					type: 'radialBar',
					height: 300,
				},
				plotOptions: {
					radialBar: {
            			track: { background: '#d3d3d3' },
						dataLabels: {
							name: { show: false },
							value: { fontSize: '42px',  fontWeight: 600,  color: '#999'},
						},
						hollow: { size: '70%' }
					},
	        	},
	        	grid : {
	        		padding: { top: -15 },
	        	},
	        	stroke: { lineCap: "round" },
	        };
	
	        var chart = new ApexCharts(document.querySelector("#request-availability"), options);
	        chart.render();
		</script>
	</div>
	<div class="span3">
		<h3><span class="header">Viagens x Entregas<small>Distribuição das requisições por classe</small></span></h3>
		<div id="trips-x-freight"></div>
		<script>
			var options = {
          		series: <?php echo json_encode(array_values($this->trips_x_freight));?>,
          		labels: <?php echo json_encode(array_keys($this->trips_x_freight));?>,
          		chart: {
          			type: 'donut',
          			height: 300,
        		},
        		plotOptions: {
				    pie: {
					    dataLabels : { offset: -15 },
				      	donut: { 
				      		size: '80%',
				      		labels: {
        						show: true,
					        	name: {
					          		show: true,
					          		fontSize: '22px',
					          		fontWeight: 'bold',
					        	},
					        	value: {
					          		show: true,
					          		fontSize: '18px',
					          		offsetY: 0,
					          		color: '#777',
					        	},
					        	total: {
					          		show: true,
					          		label: 'Total',
					          		fontSize: '22px',
					          		fontWeight: 'bold',
					          		color: '#777',
					        	}
					      	}, 
				      	}
					}
				},
				dataLabels : {
				 	style: {
				      	fontSize: '16px',
				      	fontWeight: 'bold',
				  	},
				},
				tooltip: { enabled: false },
				legend: {
			      	show: true,
			      	position: 'bottom',
			      	horizontalAlign: 'center', 
      			},
        	};

        	var chart = new ApexCharts(document.querySelector("#trips-x-freight"), options);
        	chart.render();
		</script>
	</div>
	<div class="span6">
		<h3><span class="header">Requisições finalizadas x Distância percorida<small>Comparativo entre a quantidade de requisições finalizadas e a distância percorrida</small></span></h3>
		<div id="request-x-distance"></div>
		<script>
			var options = {
				series: [{
					name: 'Quant. de Requisições',
					data: <?php echo json_encode(array_values($this->request_x_distance['request']));?>
				}, {
					name: 'Distância percorrida',
					data: <?php echo json_encode(array_values($this->request_x_distance['distance']));?>
        		}],
				chart: {
					type: 'bar',
					height: 300,
				},
				dataLabels: { enabled: false },
				xaxis: { 
					categories: <?php echo json_encode($this->request_x_distance['label']);?>,
			    },
			    yaxis: [
		          {
		            seriesName: 'Quant. de Requisições',
		            axisTicks: { show: true },
		            title: { text: "Número de Requisições" },
		          },
		          {
		            seriesName: 'Distância percorrida',
		            opposite: true,
		            axisTicks: { show: true },
		            title: { text: "Km Rodados" }
		          },
		        ],
				tooltip: {
		          	shared: true,
		          	intersect: false
		        },
		        noData: {
 	 				text: 'Não há dados disponíveis para o período informado.',
 	 				verticalAlign: 'top'
 	 			}
	        };
	
	        var chart = new ApexCharts(document.querySelector("#request-x-distance"), options);
	        chart.render();
		</script>
	</div>
</div>
<?php if (! $this->isDashboardFleetManager) { ?>
<hr>
<div class="row-fluid">
	<div class="span6">
		<h3><span class="header">Distribuição das Requisições por Órgão<small>Distribuição quantitativa das requisições por órgão</small></span></h3>
		<div id="request-per-agency"></div>
		<script>
			var options = {
          		series: [
          		<?php if ( count($this->request_per_agency) == 0) { ?>
          		<?php $data = ['']; ?>
          		 { data: [] },
          		<?php } ?>
          		<?php foreach ($this->request_per_agency as $serie => $data) { ?>
          		{
          			name: '<?php echo $serie; ?>',
          			data: <?php echo json_encode(array_values($data));?>,
          		},
          		<?php } ?>
          		],
          		chart: {
          			type: 'bar',
          			height: <?php echo count($data)*(30+10) + 92; ?>,
          			stacked: true,
        		},
        		plotOptions: {
				    bar: {
            			horizontal: true,
          			}
				},
		        yaxis: { reversed: true },
				tooltip: { enabled: false },
				dataLabels : {
				 	style: {
				      	fontSize: '16px',
				  	},
				},
				noData: {
 	 				text: 'Não há dados disponíveis para o período informado.',
 	 				verticalAlign: 'top'
 	 			}
        	};

        	var chart = new ApexCharts(document.querySelector("#request-per-agency"), options);
        	chart.render();
		</script>
	</div>
	<div class="span6">
		<h3><span class="header">Distribuição da Frota por Órgão<small>Distribuição quantitivo da frota por órgão <span class="label">Real Time</span></small></span></h3>
		<div id="fleet-per-agency"></div>
		<script type="text/javascript">
			var options = {
          		series: [
          		<?php foreach ($this->fleet_per_agency as $serie => $data) { ?>
          		{
          			name: '<?php echo $serie; ?>',
          			data: <?php echo json_encode(array_values($data));?>,
          		},
          		<?php } ?>
          		],
          		chart: {
          			type: 'bar',
          			height: <?php echo count($data)*(30+10) + 92; ?>,
          			stacked: true,
        		},
        		plotOptions: {
				    bar: {
            			horizontal: true,
          			}
				},
				tooltip: {
					enabled: true,
					shared: true,
        			intersect: false,
					y: {
				    	formatter: function(value, { series, seriesIndex, dataPointIndex, w }) {
				      		return (value > 0 ) ? value : null;
				    	}
  					},
  					x: {
				    	formatter: function(value, { series, seriesIndex, dataPointIndex, w }) {
				    		var total = 0;
				    		series.forEach(function(data, index) {
				    			total+= data[dataPointIndex];
				    		});
				      		return value + ': <strong>' + total + '</strong>';
				    	}
  					},
		        },
				dataLabels : {
				 	style: {
				      	fontSize: '16px',
				  	},
				},
		        noData: {
 	 				text: 'Não há dados disponíveis para o período informado.',
 	 				verticalAlign: 'top'
 	 			}
        	};

        	var chart = new ApexCharts(document.querySelector("#fleet-per-agency"), options);
        	chart.render();
		</script>
	</div>
</div>	
<?php } ?>
<hr>
<div class="row-fluid">
	<div class="span4">
		<h3><span class="header">Distribuição da Frota por Tipo<small>Distribuição percentual e quantitiva da frota por tipo <span class="label">Real Time</span></small></span></h3>
		<div id="fleet-per-type"></div>
		<script>
			var options = {
          		series: <?php echo json_encode(array_values($this->fleet_per_type));?>,
          		labels: <?php echo json_encode(array_keys($this->fleet_per_type));?>,
          		chart: {
          			type: 'donut',
          			height: 300,
        		},
        		plotOptions: {
				    pie: {
					    dataLabels : { offset: -15 },
				      	donut: { 
				      		size: '75%',
				      		labels: {
        						show: true,
					        	name: {
					          		show: true,
					          		fontSize: '22px',
					          		fontWeight: 'bold',
					        	},
					        	value: {
					          		show: true,
					          		fontSize: '18px',
					          		offsetY: 0,
					          		color: '#777',
					        	},
					        	total: {
					          		show: true,
					          		label: 'Total',
					          		fontSize: '22px',
					          		fontWeight: 'bold',
					          		color: '#777',
					        	}
					      	},
					    }
					}
				},
				dataLabels : {
				 	style: {
				      	fontSize: '16px',
				      	fontWeight: 'bold',
				  	},
				},
				tooltip: { enabled: false },
				legend: {
			      	show: true,
			      	position: 'bottom',
			      	horizontalAlign: 'center', 
      			}
        	};

        	var chart = new ApexCharts(document.querySelector("#fleet-per-type"), options);
        	chart.render();
		</script>
	</div>
	<div class="span4">
		<h3><span class="header">Veículos X Equipamentos<small>Distribuição percentual e quantitiva da frota por classe <span class="label">Real Time</span></small></span></h3>
		<div id="vehicle-x-equipament"></div>
		<script>
			var options = {
          		series: <?php echo json_encode(array_values($this->vehicle_x_equipament));?>,
          		labels: <?php echo json_encode(array_keys($this->vehicle_x_equipament));?>,
          		chart: {
          			type: 'donut',
          			height: 300,
        		},
        		plotOptions: {
				    pie: {
					    dataLabels : { offset: -15 },
				      	donut: { 
				      		size: '75%',
				      		labels: {
        						show: true,
					        	name: {
					          		show: true,
					          		fontSize: '22px',
					          		fontWeight: 'bold',
					        	},
					        	value: {
					          		show: true,
					          		fontSize: '18px',
					          		offsetY: 0,
					          		color: '#777',
					        	},
					        	total: {
					          		show: true,
					          		label: 'Total',
					          		fontSize: '22px',
					          		fontWeight: 'bold',
					          		color: '#777',
					        	}
					      	},
					    }
					}
				},
				dataLabels : {
				 	style: {
				      	fontSize: '16px',
				      	fontWeight: 'bold',
				  	},
				},
				tooltip: { enabled: false },
				legend: {
			      	show: true,
			      	position: 'bottom',
			      	horizontalAlign: 'center', 
      			}
        	};

        	var chart = new ApexCharts(document.querySelector("#vehicle-x-equipament"), options);
        	chart.render();
		</script>
	</div>
	<div class="span4">
		<h3><span class="header">Distribuição da Frota por Família <small>Distribuição percentual e quantitiva da frota de veículos por família <span class="label">Real Time</span></small></span></h3>
		<div id="fleet-per-family"></div>
		<script>
			var options = {
          		series: <?php echo json_encode(array_values($this->fleet_per_family));?>,
          		labels: <?php echo json_encode(array_keys($this->fleet_per_family));?>,
          		chart: {
          			type: 'donut',
          			height: 300,
        		},
        		plotOptions: {
				    pie: {
					    dataLabels : { offset: -15 },
				      	donut: { 
				      		size: '75%',
				      		labels: {
        						show: true,
					        	name: {
					          		show: true,
					          		fontSize: '22px',
					          		fontWeight: 'bold',
					        	},
					        	value: {
					          		show: true,
					          		fontSize: '18px',
					          		offsetY: 0,
					          		color: '#777',
					        	},
					        	total: {
					          		show: true,
					          		label: 'Total',
					          		fontSize: '22px',
					          		fontWeight: 'bold',
					          		color: '#777',
					        	}
					      	},
					    }
					}
				},
				dataLabels : {
				 	style: {
				      	fontSize: '16px',
				      	fontWeight: 'bold',
				  	},
				},
				tooltip: { enabled: false },
				legend: {
			      	show: true,
			      	position: 'bottom',
			      	horizontalAlign: 'center', 
      			}
        	};

        	var chart = new ApexCharts(document.querySelector("#fleet-per-family"), options);
        	chart.render();
		</script>
	</div>
</div>
<?php if ($this->isDashboardFleetManager) { ?>
<hr>
<div class="row-fluid">	
	<div class="span3">
		<h3><span class="header">Atividades Recentes<small>Acompanhe 7 últimas atividades do seu dia</small></span></h3>
	  	<?php if (count($this->activities) == 0 ) {
	  	?>
	  	<br/>
	  	<p>Nenhuma atividade registrada neste dia</p>
	  	<?php } else {?>
	  	<ul class="timeline">
	  	<?php 
	  	foreach($this->activities as $activity) {
	  		$referer = explode('?', $activity->getReferer());
	  		$referer = explode('/', trim($referer[0], '/'));
	  		$text = '';
	  		switch ($referer[0]) {
	  			case 'fleet':
	  				$badge = 'badge-success';
	  				switch ($referer[1]) {
	  					case 'new-vehicle':
	  						$text = 'Um novo Veículo <span class="label">#' .$activity->getNewValue()['id'] . '</span> foi cadastrado';
	  						break;
	  						
	  					case 'new-equipament':
	  						$text = 'Um novo Equipamento <span class="label">#' .$activity->getNewValue()['id'] . '</span> foi cadastrado';
	  						break;
	  						
	  					case 'transfer-vehicle':
	  						$text = 'O Veículo <span class="label">#' . $activity->getNewValue()['id'] . '</span> foi transferido para a unidade';
	  						break;
	  						
	  					case 'edit':
	  						$text = ($activity->getClassName() == Vehicle::getClass() ? 'O Veículo' : 'O Equipamento') . ' <span class="label">#'. $activity->getNewValue()['id'] . '</span> foi alterado';
	  						break;
	  						
	  					case 'active':
	  						$text = ($activity->getClassName() == Vehicle::getClass() ? 'O Veículo' : 'O Equipamento'). ' <span class="label">#'.$activity->getNewValue()['id'] .'</span> foi ' . ($activity->getNewValue()['active'] ? 'ativado' : 'inativado');
	  						break;
	  				}
	  				break;
	  			
	  			case 'request':
	  				$badge = 'badge-important';
	  				switch ($referer[1]) {
	  					case 'new-trip':
	  						$text = 'Um nova Viagem <span class="label">#' .$activity->getNewValue()['id'] . '</span> foi requisitada';
	  						break;
	  						
	  					case 'new-freight':
	  						$text = 'Um nova Entrega <span class="label">#' .$activity->getNewValue()['id'] . '</span> foi requisitada';
	  						break;
	  						
	  					case 'confirm':
	  						$text = ($activity->getClassName() == RequestTrip::getClass() ? 'A Viagem' : 'A Entrega' ). ' <span class="label">#' .$activity->getNewValue()['id'] . '</span> foi confirmada';
	  						break;
	  						
	  					case 'initiate':
	  						$text = ($activity->getClassName() == RequestTrip::getClass() ? 'A Viagem' : 'A Entrega' ). ' <span class="label">#' .$activity->getNewValue()['id'] . '</span> foi iniciada';
	  						break;
	  						
	  					case 'finish':
	  						$text = ($activity->getClassName() == RequestTrip::getClass() ? 'A Viagem' : 'A Entrega' ). ' <span class="label">#' .$activity->getNewValue()['id'] . '</span> foi finalizada';
	  						break;
	  						
	  					case 'cancel':
	  						$text = ($activity->getClassName() == RequestTrip::getClass() ? 'A Viagem' : 'A Entrega' ). ' <span class="label">#' .$activity->getNewValue()['id'] . '</span> foi cancelada';
	  						break;
	  						
	  				}
	  				break;
	  				
	  			default: 
	  				$badge = $activity->getClassName() == Requester::getClass() ? '' : 'badge-inverse';
	  				switch ($referer[1]) {
	  					case 'new':
	  						$text = 'Um novo ' .($activity->getClassName() == Requester::getClass() ? 'Requisitante' : 'Motorista'). ' <span class="label">#' .$activity->getNewValue()['id'] . '</span> foi cadastrado';
	  						break;
	  						
	  					case 'transfer':
	  						$text = ($activity->getClassName() == Requester::getClass() ? 'O Requisitante' : 'O Motorista'). ' <span class="label">#' .$activity->getNewValue()['id'] . '</span> foi transferido para a unidade';
	  						break;
	  						
	  					case 'edit':
	  						$text = ($activity->getClassName() == Requester::getClass() ? 'O Requisitante' : 'O Motorista'). ' <span class="label">#' .$activity->getNewValue()['id'] . '</span> foi alterado';
	  						break;
	  						
	  					case 'active':
	  						$text = ($activity->getClassName() == Requester::getClass() ? 'O Requisitante' : 'O Motorista'). ' <span class="label">#' .$activity->getNewValue()['id'] . '</span> foi ' . ($activity->getNewValue()['active'] ? 'ativado' : 'inativado');
	  						break;
	  						
	  					case 'reset-password':
	  						$text = 'A senha do ' . ($activity->getClassName() == Requester::getClass() ? 'Requisitante' : 'Motorista'). ' <span class="label">#' .$activity->getNewValue()['id'] . '</span> foi redefinida';
	  						break;
	  						
	  				}
	  				break;
	  		}
	  	?>
	  		<li class="clearfix">
	  			<span class="time"><?php echo $activity->getCreated()->format('H:i')?></span>
	  			<span class="badge <?php echo $badge; ?>"></span>
	  			<span class="text">
	  				<?php echo $text; ?><br />
	  				<small class="muted"><?php echo $activity->getReferer(); ?></small>
	  			</span>
	  		</li>
	  	<?php
	  	}
	  	?>
		</ul>
		<?php } ?>
	</div>
	<div class="span9">
		<h3><span class="header">Ranking de Motoristas <small>Posição dos motoristas de acordo com a quantidade de viagens realizadas</small></span></h3>
		<br>
		<div class="row-fluid">
			<?php for($i=0; $i<3; $i++) { ?>
			<div class="span4">
				<div class="card clearfix">
					<h1><?php echo $i+1;?>º<small>Lugar</small></h1>
					<?php if (isset($this->request_x_driver[$i])) { ?>
					<p style="text-overflow: ellipsis; overflow: hidden;"><strong style="white-space: nowrap;"><?php echo $this->request_x_driver[$i]['driver']?></strong></p>
					<p><span class="label"><?php echo number_format($this->request_x_driver[$i]['request'], 0, '', '.'); ?> Requisições</span> <span class="label"><?php echo number_format($this->request_x_driver[$i]['distance'], 0, '', '.'); ?> Km</span></p>
					<?php } else { ?>
					<p><em class="muted">Não identificado</em></p>
					<p>&nbsp;</p>
					<?php } ?>
				</div>
			</div>
			<?php } ?>
		</div>
	</div>
</div>
<?php } ?>
</div>