<?php
use Gesfrota\Services\Log;
use Gesfrota\Model\Domain\Vehicle;
use Gesfrota\Model\Domain\RequestTrip;
use Gesfrota\Model\Domain\Request;
use Gesfrota\Model\Domain\Requester;
use Gesfrota\Util\Format;
?>
<?php if ($this->isDashboardFleetManager) { ?>
<hr>
<div class="row-fluid">	
	<div class="span3">
		<h3><span class="header">Atividades Recentes<small>Acompanhe 7 últimas atividades do seu dia</small></span></h3>
	  	<?php if (count($this->activities) == 0 ) {
	  	?>
	  	<br/>
	  	<p>Nenhuma atividade registrada neste dia</p>
	  	<?php } else {?>
	  	<ul class="timeline">
	  	<?php 
	  	foreach($this->activities as $activity) {
	  		$referer = explode('?', $activity->getReferer());
	  		$referer = explode('/', trim($referer[0], '/'));
	  		$text = '';
	  		switch ($referer[0]) {
	  			case 'fleet':
	  				$badge = 'badge-success';
	  				switch ($referer[1]) {
	  					case 'new-vehicle':
	  						$text = 'Um novo Veículo <span class="label">#' . $activity->getOID() . '</span> foi cadastrado';
	  						break;
	  						
	  					case 'new-equipament':
	  						$text = 'Um novo Equipamento <span class="label">#' .$activity->getOID() . '</span> foi cadastrado';
	  						break;
	  						
	  					case 'transfer-vehicle':
	  						$text = 'O Veículo <span class="label">#' . $activity->getOID() . '</span> foi transferido para a unidade';
	  						break;
	  						
	  					case 'edit':
	  						$text = ($activity->getClassName() == Vehicle::getClass() ? 'O Veículo' : 'O Equipamento') . ' <span class="label">#'. $activity->getOID() . '</span> foi alterado';
	  						break;
	  						
	  					case 'active':
	  						$text = ($activity->getClassName() == Vehicle::getClass() ? 'O Veículo' : 'O Equipamento'). ' <span class="label">#'.$activity->getOID() .'</span> foi ' . ($activity->getNewValue()['active'] ? 'ativado' : 'inativado');
	  						break;
	  				}
	  				break;
	  			
	  			case 'request':
	  				$badge = 'badge-important';
	  				switch ($referer[1]) {
	  					case 'new-trip':
	  						$text = 'Um nova Viagem <span class="label">#' .$activity->getOID() . '</span> foi requisitada';
	  						break;
	  						
	  					case 'new-freight':
	  						$text = 'Um nova Entrega <span class="label">#' .$activity->getOID() . '</span> foi requisitada';
	  						break;
	  						
	  					case 'confirm':
	  						$text = ($activity->getClassName() == RequestTrip::getClass() ? 'A Viagem' : 'A Entrega' ). ' <span class="label">#' .$activity->getOID() . '</span> foi confirmada';
	  						break;
	  						
	  					case 'initiate':
	  						$text = ($activity->getClassName() == RequestTrip::getClass() ? 'A Viagem' : 'A Entrega' ). ' <span class="label">#' .$activity->getOID() . '</span> foi iniciada';
	  						break;
	  						
	  					case 'finish':
	  						$text = ($activity->getClassName() == RequestTrip::getClass() ? 'A Viagem' : 'A Entrega' ). ' <span class="label">#' .$activity->getOID() . '</span> foi finalizada';
	  						break;
	  						
	  					case 'cancel':
	  						$text = ($activity->getClassName() == RequestTrip::getClass() ? 'A Viagem' : 'A Entrega' ). ' <span class="label">#' .$activity->getOID() . '</span> foi cancelada';
	  						break;
	  						
	  					case 'decline':
	  					    $text = ($activity->getClassName() == RequestTrip::getClass() ? 'A Viagem' : 'A Entrega' ). ' <span class="label">#' . $activity->getOID() . '</span> foi recusada';
	  					    break;
	  						
	  				}
	  				break;
	  				
	  			default: 
	  				$badge = $activity->getClassName() == Requester::getClass() ? '' : 'badge-inverse';
	  				switch ($referer[1]) {
	  					case 'new':
	  						$text = 'Um novo ' .($activity->getClassName() == Requester::getClass() ? 'Requisitante' : 'Motorista'). ' <span class="label">#' .$activity->getOID() . '</span> foi cadastrado';
	  						break;
	  						
	  					case 'transfer':
	  						$text = ($activity->getClassName() == Requester::getClass() ? 'O Requisitante' : 'O Motorista'). ' <span class="label">#' .$activity->getOID() . '</span> foi transferido para a unidade';
	  						break;
	  						
	  					case 'edit':
	  						$text = ($activity->getClassName() == Requester::getClass() ? 'O Requisitante' : 'O Motorista'). ' <span class="label">#' .$activity->getOID() . '</span> foi alterado';
	  						break;
	  						
	  					case 'active':
	  						$text = ($activity->getClassName() == Requester::getClass() ? 'O Requisitante' : 'O Motorista'). ' <span class="label">#' .$activity->getOID() . '</span> foi ' . ($activity->getNewValue()['active'] ? 'ativado' : 'inativado');
	  						break;
	  						
	  					case 'reset-password':
	  						$text = 'A senha do ' . ($activity->getClassName() == Requester::getClass() ? 'Requisitante' : 'Motorista'). ' <span class="label">#' .$activity->getOID() . '</span> foi redefinida';
	  						break;
	  						
	  				}
	  				break;
	  		}
	  	?>
	  		<li class="clearfix">
	  			<span class="time"><?php echo $activity->getCreated()->format('H:i')?></span>
	  			<span class="badge <?php echo $badge; ?>"></span>
	  			<span class="text">
	  				<?php echo $text; ?><br />
	  				<small class="muted"><?php echo $activity->getReferer(); ?></small>
	  			</span>
	  		</li>
	  	<?php
	  	}
	  	?>
		</ul>
		<?php } ?>
	</div>
	<div class="span9">
		<h3><span class="header">Ranking de Motoristas <small>Posição dos motoristas de acordo com a quantidade de viagens realizadas</small></span></h3>
		<br>
		<div class="row-fluid">
			<?php for($i=0; $i<3; $i++) { ?>
			<div class="span4">
				<div class="card clearfix">
					<h1><?php echo $i+1;?>º<small>Lugar</small></h1>
					<?php if (isset($this->request_x_driver[$i])) { ?>
					<p style="text-overflow: ellipsis; overflow: hidden;"><strong style="white-space: nowrap;"><?php echo $this->request_x_driver[$i]['driver']?></strong></p>
					<p><span class="label"><?php echo number_format($this->request_x_driver[$i]['request'], 0, '', '.'); ?> Requisições</span> <span class="label"><?php echo number_format($this->request_x_driver[$i]['distance'], 0, '', '.'); ?> Km</span></p>
					<?php } else { ?>
					<p><em class="muted">Não identificado</em></p>
					<p>&nbsp;</p>
					<?php } ?>
				</div>
			</div>
			<?php } ?>
		</div>
	</div>
<?php } ?>
</div>